export enum ResMessage {
  OK = 'OK',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DB_ERROR = 'DB_ERROR',

  // Auth
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  INVALID_USER = 'INVALID_USER',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  ACCESS_DENIED = 'ACCESS_DENIED',

  // Category
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
}

export enum ResCode {
  OK = 0,
  INTERNAL_SERVER_ERROR = 500,
  DB_ERROR = 501,

  // Auth
  EMAIL_EXISTS = 11000,
  INVALID_USER = 11001,
  INVALID_PASSWORD = 11002,
  ACCESS_DENIED = 11003,

  // Category
  CATEGORY_NOT_FOUND = 12000,
}
